raw_names = [
    "Funksjoner for bydelene i Oslo",
    "Fylkeskommunale funksjoner",
    "Kommunale funksjoner",
    "Detaljerte regnskapstall driftsregnskapet, bydeler i Oslo",
    "Detaljerte regnskapstall driftsregnskapet",
    "Finansielle grunnlagsdata, (fylkes)kommunekasse og konsoliderte regnskap",
    "Finansielle grunnlagsdata, kommunekonsern_",
    "Finansielle grunnlagsdata, fylkeskommunekonsern_",
    "Finansielle nøkkeltall i prosent av brutto driftsinntekter, konsern",
    "Finansielle nøkkeltall i kroner per innbygger, kasse og konsolidert kommune",
    "Finansielle nøkkeltall i kroner per innbygger, kommunekonsern",
    "Finansielle nøkkeltall i kroner per innbygger, fylkeskommunekonsern",
    "Finansiering av driften, kommunekonsern",
    "Finansiering av driften, fylkeskommunekonsern",
    "Finansiering av investeringene, konsern",
    "Hovedtall for drift, investering og finansiering, konsern",
    "Utgifter til tjenesteområdene",
    "Økonomisk oversikt balanse, konsern",
    "Økonomisk oversikt balanse, kasse og konsolidert",
    "Økonomisk oversikt drift, konsern",
    "Økonomisk oversikt drift, kasse og konsolidert",
    "Økonomisk oversikt investering, kasse og konsolidert",
    "Økonomisk oversikt investering, kommunekonsern",
    "Økonomisk oversikt investering, fylkeskommunekonsern",
    "Uttrekk for Kommuner 2020-2023 (uten aggregerte regioner)",
    "Uttrekk for Kommuner 2024- (uten aggregerte regioner)",
    "Uttrekk for Fylkeskommuner 2020-2023 (uten aggregerte regioner)",
    "Uttrekk for Fylkeskommuner 2024- (uten aggregerte regioner)",
    "Uttrekk for Alle fylker 2015-2023",
    "Uttrekk for Alle fylkeskommuner",
    "Uttrekk for Alle kommuner",
    "Uttrekk for Alle fylker",
    "Uttrekk for Fylker 2024-",
    "Uttrekk for Kommuner 2020-2023",
    "Uttrekk for Kommuner -2019",
    "Uttrekk for Fylker 2020-2023",
    "Uttrekk for Kommuner 2024-",
    "Uttrekk for Fylker -2019",
    "Uttrekk for KOSTRA-grupperinger",
    "Uttrekk for Landet",
    "Uttrekk for Fylkeskommuner 2020-2023",
    "Uttrekk for Fylkeskommuner -2019",
    "Uttrekk for Fylkeskommuner 2024-",
    "Uttrekk for KOSTRA-fylkeskommunegrupperinger",
]

# These need suffix in id
add_suffix = [
    "Uttrekk for Alle fylkeskommuner",
    "Uttrekk for Alle kommuner",
    "Uttrekk for Kommuner -2019",
    "Uttrekk for KOSTRA-grupperinger",
    "Uttrekk for Fylker 2020-2023",
    "Uttrekk for Kommuner 2020-2023",
]

# map directly
special_cases = {
    "Uttrekk for Kommuner -2019": "uttrekk_for_kommuner_-2019_kladd",
    "Uttrekk for Kommuner 2020-2023 (uten aggregerte regioner)": "uttrekk_for_kommuner_2020-2023_uten_aggregerte_regioner",
    "Uttrekk for Fylkeskommuner 2024-": "uttrekk_for_fylkeskommuner_2024-_kladd",
    "Uttrekk for Kommuner 2024-": "uttrekk_for_kommuner_2024-_kladd",
    "Uttrekk for Fylker -2019": "uttrekk_for_fylker_-2019_kladd",
    "Kommunale funksjoner": "uttrekk_for_detaljerte_regnskapstall_driftsregnskapet_kommuner_funksjoner",
    "Uttrekk for Landet": "uttrekk_for_landet_kommuner_kladd",
}


ids = [
    "uttrekk_for_funksjoner_for_bydelene_i_oslo",
    "uttrekk_for_fylkeskommunale_funksjoner",
    "uttrekk_for_detaljerte_regnskapstall_driftsregnskapet_kommuner_funksjoner",
    "uttrekk_for_detaljerte_regnskapstall_driftsregnskapet_bydeler_i_oslo",
    "uttrekk_for_detaljerte_regnskapstall_driftsregnskapet",
    "uttrekk_for_finansielle_grunnlagsdata_fylkeskommunekasse_og_konsoliderte_regnskap",
    "uttrekk_for_finansielle_grunnlagsdata_kommunekonsern_",
    "uttrekk_for_finansielle_grunnlagsdata_fylkeskommunekonsern_",
    "uttrekk_for_finansielle_nokkeltall_i_prosent_av_brutto_driftsinntekter_konsern",
    "uttrekk_for_finansielle_nokkeltall_i_kroner_per_innbygger_kasse_og_konsolidert_kommune",
    "uttrekk_for_finansielle_nokkeltall_i_kroner_per_innbygger_kommunekonsern",
    "uttrekk_for_finansielle_nokkeltall_i_kroner_per_innbygger_fylkeskommunekonsern",
    "uttrekk_for_finansiering_av_driften_kommunekonsern",
    "uttrekk_for_finansiering_av_driften_fylkeskommunekonsern",
    "uttrekk_for_finansiering_av_investeringene_konsern",
    "uttrekk_for_hovedtall_for_drift_investering_og_finansiering_konsern",
    "uttrekk_for_utgifter_til_tjenesteomradene",
    "uttrekk_for_okonomisk_oversikt_balanse_konsern",
    "uttrekk_for_okonomisk_oversikt_balanse_kasse_og_konsolidert",
    "uttrekk_for_okonomisk_oversikt_drift_konsern",
    "uttrekk_for_okonomisk_oversikt_drift_kasse_og_konsolidert",
    "uttrekk_for_okonomisk_oversikt_investering_kasse_og_konsolidert",
    "uttrekk_for_okonomisk_oversikt_investering_kommunekonsern",
    "uttrekk_for_okonomisk_oversikt_investering_fylkeskommunekonsern",
    "uttrekk_for_kommuner_2020-2023_uten_aggregerte_regioner",
    "uttrekk_for_kommuner_2024-_uten_aggregerte_regioner",
    "uttrekk_for_fylkeskommuner_2020-2023_uten_aggregerte_regioner",
    "uttrekk_for_fylkeskommuner_2024-_uten_aggregerte_regioner",
    "uttrekk_for_alle_fylker_2015-2023",
    "uttrekk_for_alle_fylkeskommuner_kladd",
    "uttrekk_for_alle_kommuner_kladd",
    "uttrekk_for_alle_fylker",
    "uttrekk_for_fylker_2024-",
    "uttrekk_for_kommuner_2020-2023_kladd",
    "uttrekk_for_kommuner_-2019_kladd",
    "uttrekk_for_fylker_2020-2023_kladd",
    "uttrekk_for_kommuner_2024-_kladd",
    "uttrekk_for_fylker_-2019_kladd",
    "uttrekk_for_kostra-grupperinger_kladd",
    "uttrekk_for_landet_kommuner_kladd",
    "uttrekk_for_fylkeskommuner_2020-2023",
    "uttrekk_for_fylkeskommuner_-2019",
    "uttrekk_for_fylkeskommuner_2024-_kladd",
    "uttrekk_for_kostra-fylkeskommunegrupperinger",
]
