from datetime import date

VARDEF_EXAMPLE_DEFINITION_ID = "wypvb3wd"
VARDEF_EXAMPLE_ACTIVE_GROUP = "dapla-felles-developers"
VARDEF_EXAMPLE_DATE = date(1970, 1, 1)
JUPYTERHUB_USER = "JUPYTERHUB_USER"
DAPLA_REGION = "DAPLA_REGION"
DAPLA_GROUP_CONTEXT = "DAPLA_GROUP_CONTEXT"
DAPLA_SERVICE = "DAPLA_SERVICE"
